debug: true
server:
  error:
    include-stacktrace: never
spring:
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
  datasource:
    url: jdbc:postgresql://dumbo.db.elephantsql.com:5432/${PGSQL_DB}
    username: ${PGSQL_USERNAME}
    password: ${PGSQL_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
openai_key: ${OPENAI_KEY}